# Generated by Django 5.1.3 on 2024-11-24 09:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProducerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produce_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahakorn.producertype')),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('loan_date', models.DateField()),
                ('payed', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahakorn.member')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('equipment_type', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahakorn.member')),
            ],
        ),
        migrations.CreateModel(
            name='CommonFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('total_paid', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_due', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahakorn.member')),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_date', models.DateField()),
                ('r_date', models.DateField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahakorn.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahakorn.member')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahakorn.member')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahakorn.itemtype')),
            ],
        ),
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahakorn.itemtype')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahakorn.member')),
                ('p_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahakorn.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_paid', models.FloatField()),
                ('date', models.DateField()),
                ('market_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahakorn.marketitem')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sahakorn.member')),
            ],
        ),
    ]
