# Generated by Django 5.1.3 on 2024-11-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sahakorn", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="type",
        ),
        migrations.AddField(
            model_name="stock",
            name="item_type",
            field=models.ManyToManyField(to="sahakorn.itemtype"),
        ),
        migrations.RemoveField(
            model_name="member",
            name="produce_type",
        ),
        migrations.AddField(
            model_name="member",
            name="produce_type",
            field=models.ManyToManyField(to="sahakorn.producertype"),
        ),
    ]
