# Generated by Django 5.1.3 on 2024-11-24 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sahakorn", "0002_remove_stock_type_stock_item_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loans",
            old_name="payed",
            new_name="paid",
        ),
        migrations.RenameField(
            model_name="marketitem",
            old_name="p_name",
            new_name="stock",
        ),
        migrations.RemoveField(
            model_name="marketitem",
            name="producer",
        ),
        migrations.AlterField(
            model_name="loans",
            name="amount",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.RemoveField(
            model_name="marketitem",
            name="item_type",
        ),
        migrations.AlterField(
            model_name="stock",
            name="quantity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                condition=models.Q(("r_date__gte", models.F("s_date"))),
                name="equipment must be return after borrowing date.",
            ),
        ),
        migrations.AddConstraint(
            model_name="loans",
            constraint=models.CheckConstraint(
                condition=models.Q(("paid__lte", models.F("amount"))),
                name="paid amount less than borrow amount",
            ),
        ),
        migrations.AddField(
            model_name="marketitem",
            name="item_type",
            field=models.ManyToManyField(to="sahakorn.itemtype"),
        ),
    ]
